container: add fat32.img

diff --git a/container/Makefile b/container/Makefile
--- a/container/Makefile
+++ b/container/Makefile
@@ -25,8 +25,42 @@ build-push-multi:
 		--push \
 		-t $(IMAGE_NAME) . # --no-cache
 
+build-fat32:
+	@if [ "$$(id -u)" -ne 0 ]; then \
+		echo "Please use sudo to run this make target!"; \
+		exit 1; \
+	fi
+	@if ! command -v parted >/dev/null 2>&1; then \
+		echo "parted not found"; \
+		exit 1; \
+	fi
+	@if ! command -v losetup >/dev/null 2>&1; then \
+		echo "losetup not found"; \
+		exit 1; \
+	fi
+	@if ! command -v mkfs.vfat >/dev/null 2>&1; then \
+		echo "mkfs.vfat not found"; \
+		echo "Run apt install dosfstools on Debian/Ubuntu"; \
+		exit 1; \
+	fi
+
+	dd if=/dev/zero of=./fat32.img bs=1M count=64
+	parted -s ./fat32.img -- \
+		mklabel msdos\
+		mkpart primary fat32 1MiB 100%
+	LOOP_DEVICE=$$(losetup -f --show -P ./fat32.img); \
+		mkfs.vfat $${LOOP_DEVICE}p1; \
+		mkdir -p /mnt/fat32; \
+		mount $${LOOP_DEVICE}p1 /mnt/fat32; \
+		wget -O /mnt/fat32/email.txt https://ramix.org/linus.html; \
+		umount /mnt/fat32; \
+		losetup -d $${LOOP_DEVICE}; \
+		rm -rf /mnt/fat32
+	zip ./fat32.img.zip ./fat32.img
+	rm -f ./fat32.img
+
 # inside docker
 build-rootfs:
 	make -C $(BUILD_ROOT_PATH) ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu- qemu_riscv64_virt_defconfig
 	make -C $(BUILD_ROOT_PATH) ARCH=riscv64 CROSS_COMPILE=riscv64-linux-gnu- -j$(nproc)
-	cp $(BUILD_ROOT_PATH)/output/images/rootfs.ext2 /zju-os/tool/container
+	zip ./rootfs.ext2.zip $(BUILD_ROOT_PATH)/output/images/rootfs.ext2
