container: add spike

diff --git a/zjugit-ci/Makefile b/zjugit-ci/Makefile
--- a/zjugit-ci/Makefile
+++ b/zjugit-ci/Makefile
@@ -1,10 +1,15 @@
 SERVICE_NAME := zju-os-runner
 
+.PHONY: all clean register
+
 all:
-	docker compose up
+	@if [ ! -f config/config.toml ]; then \
+		echo "config/config.toml not found, please run 'make register TOKEN=\"<your_token>\"' first"; \
+		exit 1; \
+	fi
+	docker compose up -d
 
 register:
-	# check if config/config.toml exists
 	@if [ -f config/config.toml ]; then \
 		echo "config/config.toml already exists, please remove it first"; \
 		exit 1; \
@@ -13,7 +18,6 @@ register:
 		echo "Please provide TOKEN, e.g. make register TOKEN=\"<your_token>\""; \
 		exit 1; \
 	fi
-	# register the runner
 	docker compose run --rm $(SERVICE_NAME) register \
 		--non-interactive \
 		--url "https://git.zju.edu.cn/" \
@@ -21,10 +25,6 @@ register:
 		--executor "docker" \
 		--docker-image git.zju.edu.cn:5050/os/tool:latest \
 		--description "zju-os-runner"
-	make run
-
-run:
-	docker compose run --rm $(SERVICE_NAME) run
 
 clean:
 	docker compose down -v --remove-orphans
